begin;

-- Optional reset of seed-owned content
delete from team_progress;
delete from kickoff_progress;
delete from checkpoints;
delete from teams;
delete from routes;

-- Routes
insert into routes (code, name) values
  ('A', 'Route A'),
  ('B', 'Route B'),
  ('C', 'Route C'),
  ('D', 'Route D'),
  ('E', 'Route E'),
  ('F', 'Route F')
on conflict (code) do update set name = excluded.name;

-- Teams
insert into teams (code, name, color_hex, route_id, kickoff_challenge)
select v.code, v.name, v.color_hex, r.id, v.kickoff_challenge
from (values
  ('pink', 'Pink Team', '#ec4899', 'A', 'Find the vintage NOPSI generator sculpture in the lobby and take a team selfie.'),
  ('red', 'Red Team', '#ef4444', 'B', 'Ask a hotel staff member for their favorite New Orleans restaurant and record the answer.'),
  ('yellow', 'Yellow Team', '#facc15', 'C', 'Take a photo of something gold or brass inside NOPSI.'),
  ('purple', 'Purple Team', '#a855f7', 'D', 'Create a quick 5-second jazz pose video in the lobby.'),
  ('green', 'Green Team', '#22c55e', 'E', 'Find a plant or greenery inside or just outside the hotel and take a team photo.'),
  ('silver', 'Silver Team', '#94a3b8', 'A', 'Find something metallic or reflective in the lobby and snap a photo.'),
  ('black', 'Black Team', '#0f172a', 'B', 'Take a dramatic film-noir style photo in the NOPSI entrance.'),
  ('white', 'White Team', '#f8fafc', 'C', 'Take a bright group selfie under the lobby lights.'),
  ('blue', 'Blue Team', '#3b82f6', 'F', 'Find something blue in the lobby or a street sign outside and photograph it.')
) as v(code, name, color_hex, route_code, kickoff_challenge)
join routes r on r.code = v.route_code
on conflict (code) do update
set name = excluded.name,
    color_hex = excluded.color_hex,
    route_id = excluded.route_id,
    kickoff_challenge = excluded.kickoff_challenge;

-- Kickoff progress baseline
insert into kickoff_progress (team_id, status, points_awarded, proof_url, completed_at)
select t.id, 'pending', 10, null, null
from teams t
on conflict (team_id) do update
set status = excluded.status,
    points_awarded = excluded.points_awarded,
    proof_url = excluded.proof_url,
    completed_at = excluded.completed_at,
    updated_at = now();

-- Compatibility: ensure difficulty column exists even if migration 004 wasn't applied yet
alter table checkpoints
  add column if not exists difficulty_level text not null default 'medium'
  check (difficulty_level in ('medium','hard'));

-- Checkpoints
insert into checkpoints (
  route_id, order_index, title, clue_text, task_text, unlock_answer, answer_text, unlock_qr, latitude, longitude, enable_gps, proof_type, points, public_checkpoint_label, participant_clue_text, participant_task_text_pre_solve, participant_success_text_post_solve, internal_location_name, host_verification_task_text, difficulty_level
)
select
  r.id, v.order_index, v.title, v.clue_text, v.task_text, v.unlock_answer, v.answer_text, v.unlock_qr, v.latitude, v.longitude, v.enable_gps, v.proof_type, v.points, v.public_checkpoint_label, v.participant_clue_text, v.participant_task_text_pre_solve, v.participant_success_text_post_solve, v.internal_location_name, v.host_verification_task_text, v.difficulty_level
from (values
  ('A', 1, 'Lafayette Square', 'Begin where office towers give way to a patch of green that feels older than the surrounding glass and traffic. Large oaks cast shade over lunch crowds while a raised monument anchors the center of the grounds. This stop honors a French military ally tied to early American independence. Stand where business district rush slows into a pocket of benches, iron fencing, and open lawn. If you can see a formal civic corridor nearby, you are in the right zone. Take a team photo that clearly shows your group at the correct landmark area.', 'Take a team photo that clearly shows your group at the correct landmark area.', 'lafayette square', 'lafayette square', 'QR-A-1', 29.9496, -90.0704, true, 'photo', 10, 'Checkpoint 1', 'Begin where office towers give way to a patch of green that feels older than the surrounding glass and traffic. Large oaks cast shade over lunch crowds while a raised monument anchors the center of the grounds. This stop honors a French military ally tied to early American independence. Stand where business district rush slows into a pocket of benches, iron fencing, and open lawn. If you can see a formal civic corridor nearby, you are in the right zone. Take a team photo that clearly shows your group at the correct landmark area.', 'Take a team photo that clearly shows your group at the correct landmark area.', 'Nice solve. Confirm your proof upload and keep moving.', 'Lafayette Square', 'Team photo pointing dramatically at the central statue.', 'medium'),
  ('A', 2, 'Bourbon Street Sign', 'Head toward the Quarter corridor where balconies stack high and sound spills into the street day and night. Neon, live bands, and dense foot traffic make this one of the city’s most photographed stretches. You are looking for the most famous party spine in the neighborhood, not the refined arts blocks nearby. Keep moving until the energy is unmistakably loud and theatrical. Street signs here are often snapped by visitors proving they made it to this iconic zone. Take a team photo that clearly proves you reached the correct street checkpoint.', 'Take a team photo that clearly proves you reached the correct street checkpoint.', 'bourbon street', 'bourbon street', 'QR-A-2', 29.9581, -90.0656, true, 'photo', 10, 'Checkpoint 2', 'Head toward the Quarter corridor where balconies stack high and sound spills into the street day and night. Neon, live bands, and dense foot traffic make this one of the city’s most photographed stretches. You are looking for the most famous party spine in the neighborhood, not the refined arts blocks nearby. Keep moving until the energy is unmistakably loud and theatrical. Street signs here are often snapped by visitors proving they made it to this iconic zone. Take a team photo that clearly proves you reached the correct street checkpoint.', 'Take a team photo that clearly proves you reached the correct street checkpoint.', 'Checkpoint solved. Keep your pace and unlock the next clue.', 'Bourbon Street Sign', 'Team photo with a Bourbon Street sign.', 'medium'),
  ('A', 3, 'Jackson Square', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a team photo featuring the most recognizable historic element at this location.', 'Take a team photo featuring the most recognizable historic element at this location.', 'jackson square', 'jackson square', 'QR-A-3', 29.9574, -90.0623, true, 'photo', 15, 'Checkpoint 3', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a team photo featuring the most recognizable historic element at this location.', 'Take a team photo featuring the most recognizable historic element at this location.', 'Great work. You solved this checkpoint.', 'Jackson Square', 'Team photo with Andrew Jackson visible.', 'hard'),
  ('A', 4, 'Café du Monde', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature food-themed challenge at this stop.', 'Take a photo proving your team completed the signature food-themed challenge at this stop.', 'cafe du monde', 'cafe du monde', 'QR-A-4', 29.9577, -90.0621, true, 'photo', 15, 'Checkpoint 4', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature food-themed challenge at this stop.', 'Take a photo proving your team completed the signature food-themed challenge at this stop.', 'Solved. Upload confirmed—time for the final leg.', 'Café du Monde', 'Team photo showing a powdered sugar mustache.', 'medium'),
  ('A', 5, 'Mulate''s', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'mulates', 'mulates', 'QR-A-5', 29.9435, -90.0703, true, 'video', 20, 'Final checkpoint', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'Final checkpoint solved. Await host wrap-up.', 'Mulate''s', '10-second Cajun two-step video at Mulate''s.', 'medium'),
  ('B', 1, 'Canal Street Streetcar', 'Start on the broad downtown edge where the Quarter begins and movement channels in multiple directions. Rails run through this corridor and transit is part of the visual identity from end to end. You should notice a constant flow of riders, storefronts, and traffic converging in one linear spine. This location feels more open and commercial than the narrower historic lanes nearby. If you can spot track-based transport and heavy cross-city movement, you are on target. Take a photo or action shot that proves you found the transit-themed checkpoint.', 'Take a photo or action shot that proves you found the transit-themed checkpoint.', 'canal street', 'canal street', 'QR-B-1', 29.9537, -90.0716, true, 'photo', 10, 'Checkpoint 1', 'Start on the broad downtown edge where the Quarter begins and movement channels in multiple directions. Rails run through this corridor and transit is part of the visual identity from end to end. You should notice a constant flow of riders, storefronts, and traffic converging in one linear spine. This location feels more open and commercial than the narrower historic lanes nearby. If you can spot track-based transport and heavy cross-city movement, you are on target. Take a photo or action shot that proves you found the transit-themed checkpoint.', 'Take a photo or action shot that proves you found the transit-themed checkpoint.', 'Solved. Keep moving to checkpoint 2.', 'Canal Street Streetcar', 'Photo of a moving streetcar on Canal Street.', 'medium'),
  ('B', 2, 'Royal Street', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Capture a short video showing your team interacting with the artistic or musical energy of the location.', 'Capture a short video showing your team interacting with the artistic or musical energy of the location.', 'royal street', 'royal street', 'QR-B-2', 29.9589, -90.0645, true, 'video', 15, 'Checkpoint 2', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Capture a short video showing your team interacting with the artistic or musical energy of the location.', 'Capture a short video showing your team interacting with the artistic or musical energy of the location.', 'Checkpoint solved. Unlock your next clue.', 'Royal Street', 'Short video of a teammate dancing near a street musician.', 'hard'),
  ('B', 3, 'Jackson Square', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a team photo featuring the most recognizable landmark element in the area.', 'Take a team photo featuring the most recognizable landmark element in the area.', 'jackson square', 'jackson square', 'QR-B-3', 29.9574, -90.0623, true, 'photo', 15, 'Checkpoint 3', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a team photo featuring the most recognizable landmark element in the area.', 'Take a team photo featuring the most recognizable landmark element in the area.', 'Solved. Team is on track.', 'Jackson Square', 'Team photo with St. Louis Cathedral or Andrew Jackson statue visible.', 'hard'),
  ('B', 4, 'Pat O''Brien''s Flaming Fountain', 'Look for a tucked-away courtyard linked to a famous cocktail stop in the Quarter. Inside, one feature is memorable because fire appears above water in the same focal point. This isn’t a street-corner landmark, so you need to slip off the main path to locate it. The atmosphere is theatrical, photogenic, and often packed with visitors taking dramatic poses. If your team enters a hidden patio and immediately knows it is unique, you found the right place. Take a dramatic team photo proving you found the correct hidden courtyard feature.', 'Take a dramatic team photo proving you found the correct hidden courtyard feature.', 'pat obrien', 'pat obrien', 'QR-B-4', 29.9579, -90.0653, true, 'photo', 15, 'Checkpoint 4', 'Look for a tucked-away courtyard linked to a famous cocktail stop in the Quarter. Inside, one feature is memorable because fire appears above water in the same focal point. This isn’t a street-corner landmark, so you need to slip off the main path to locate it. The atmosphere is theatrical, photogenic, and often packed with visitors taking dramatic poses. If your team enters a hidden patio and immediately knows it is unique, you found the right place. Take a dramatic team photo proving you found the correct hidden courtyard feature.', 'Take a dramatic team photo proving you found the correct hidden courtyard feature.', 'Solved. Final checkpoint ahead.', 'Pat O''Brien''s Flaming Fountain', 'Hurricane-style team pose around the flaming fountain.', 'hard'),
  ('B', 5, 'Mulate''s', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'mulates', 'mulates', 'QR-B-5', 29.9435, -90.0703, true, 'video', 20, 'Final checkpoint', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'Route complete. Await host confirmation.', 'Mulate''s', '10-second Cajun two-step video at Mulate''s.', 'medium'),
  ('C', 1, 'Gallier Hall', 'Head to a formal civic landmark on the major boulevard where parades and ceremonies often pass. White columns and symmetrical architecture make this stop stand out from nearby modern facades. The building reflects an older era of city governance and public display. From the sidewalk, the frontage feels stately, open, and built for official gatherings. You are seeking a classic municipal structure, not a retail or nightlife destination. Take a team photo featuring the most recognizable architectural detail at this civic landmark.', 'Take a team photo featuring the most recognizable architectural detail at this civic landmark.', 'gallier hall', 'gallier hall', 'QR-C-1', 29.9516, -90.0702, true, 'photo', 10, 'Checkpoint 1', 'Head to a formal civic landmark on the major boulevard where parades and ceremonies often pass. White columns and symmetrical architecture make this stop stand out from nearby modern facades. The building reflects an older era of city governance and public display. From the sidewalk, the frontage feels stately, open, and built for official gatherings. You are seeking a classic municipal structure, not a retail or nightlife destination. Take a team photo featuring the most recognizable architectural detail at this civic landmark.', 'Take a team photo featuring the most recognizable architectural detail at this civic landmark.', 'Great solve. Keep going.', 'Gallier Hall', 'Team photo at Gallier Hall with column count visible or noted.', 'hard'),
  ('C', 2, 'Bourbon Street Sign', 'Head toward the Quarter corridor where balconies stack high and sound spills into the street day and night. Neon, live bands, and dense foot traffic make this one of the city’s most photographed stretches. You are looking for the most famous party spine in the neighborhood, not the refined arts blocks nearby. Keep moving until the energy is unmistakably loud and theatrical. Street signs here are often snapped by visitors proving they made it to this iconic zone. Take a group photo that clearly proves your team reached the correct street checkpoint.', 'Take a group photo that clearly proves your team reached the correct street checkpoint.', 'bourbon street', 'bourbon street', 'QR-C-2', 29.9581, -90.0656, true, 'photo', 10, 'Checkpoint 2', 'Head toward the Quarter corridor where balconies stack high and sound spills into the street day and night. Neon, live bands, and dense foot traffic make this one of the city’s most photographed stretches. You are looking for the most famous party spine in the neighborhood, not the refined arts blocks nearby. Keep moving until the energy is unmistakably loud and theatrical. Street signs here are often snapped by visitors proving they made it to this iconic zone. Take a group photo that clearly proves your team reached the correct street checkpoint.', 'Take a group photo that clearly proves your team reached the correct street checkpoint.', 'Solved. Next clue unlocked soon.', 'Bourbon Street Sign', 'Group photo with a Bourbon Street sign.', 'medium'),
  ('C', 3, 'Café du Monde', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature treat challenge at this stop.', 'Take a photo proving your team completed the signature treat challenge at this stop.', 'cafe du monde', 'cafe du monde', 'QR-C-3', 29.9577, -90.0621, true, 'photo', 15, 'Checkpoint 3', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature treat challenge at this stop.', 'Take a photo proving your team completed the signature treat challenge at this stop.', 'Solved. Keep your momentum.', 'Café du Monde', 'Photo showing beignet or powdered sugar evidence.', 'medium'),
  ('C', 4, 'French Market', 'Move toward the long commercial corridor where open-air stalls and vendor rows stretch block after block. This area blends shopping, snacks, souvenirs, and constant pedestrian flow. It feels historic but active, with changing displays and a market rhythm throughout the day. You should see repeated booth-style setups instead of a single storefront destination. If the scene looks like a continuous bazaar near the Quarter edge, you are in the correct zone. Take a team photo that clearly proves you found the market checkpoint.', 'Take a team photo that clearly proves you found the market checkpoint.', 'french market', 'french market', 'QR-C-4', 29.9615, -90.0572, true, 'photo', 15, 'Checkpoint 4', 'Move toward the long commercial corridor where open-air stalls and vendor rows stretch block after block. This area blends shopping, snacks, souvenirs, and constant pedestrian flow. It feels historic but active, with changing displays and a market rhythm throughout the day. You should see repeated booth-style setups instead of a single storefront destination. If the scene looks like a continuous bazaar near the Quarter edge, you are in the correct zone. Take a team photo that clearly proves you found the market checkpoint.', 'Take a team photo that clearly proves you found the market checkpoint.', 'Checkpoint solved. Final stop remains.', 'French Market', 'Team photo with French Market sign or vendor stalls.', 'hard'),
  ('C', 5, 'Mulate''s', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'mulates', 'mulates', 'QR-C-5', 29.9435, -90.0703, true, 'video', 20, 'Final checkpoint', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'Route complete. Await host confirmation.', 'Mulate''s', '10-second Cajun two-step video at Mulate''s.', 'medium'),
  ('D', 1, 'Canal Street', 'Start on the broad downtown edge where the Quarter begins and movement channels in multiple directions. Rails run through this corridor and transit is part of the visual identity from end to end. You should notice a constant flow of riders, storefronts, and traffic converging in one linear spine. This location feels more open and commercial than the narrower historic lanes nearby. If you can spot track-based transport and heavy cross-city movement, you are on target. Take a team photo that clearly shows the main corridor or movement feature of this checkpoint.', 'Take a team photo that clearly shows the main corridor or movement feature of this checkpoint.', 'canal street', 'canal street', 'QR-D-1', 29.9537, -90.0716, true, 'photo', 10, 'Checkpoint 1', 'Start on the broad downtown edge where the Quarter begins and movement channels in multiple directions. Rails run through this corridor and transit is part of the visual identity from end to end. You should notice a constant flow of riders, storefronts, and traffic converging in one linear spine. This location feels more open and commercial than the narrower historic lanes nearby. If you can spot track-based transport and heavy cross-city movement, you are on target. Take a team photo that clearly shows the main corridor or movement feature of this checkpoint.', 'Take a team photo that clearly shows the main corridor or movement feature of this checkpoint.', 'Solved. Keep moving.', 'Canal Street', 'Team shot with Canal Street background.', 'medium'),
  ('D', 2, 'Pat O''Brien''s Flaming Fountain', 'Look for a tucked-away courtyard linked to a famous cocktail stop in the Quarter. Inside, one feature is memorable because fire appears above water in the same focal point. This isn’t a street-corner landmark, so you need to slip off the main path to locate it. The atmosphere is theatrical, photogenic, and often packed with visitors taking dramatic poses. If your team enters a hidden patio and immediately knows it is unique, you found the right place. Create a dramatic group pose proving you found the hidden courtyard checkpoint.', 'Create a dramatic group pose proving you found the hidden courtyard checkpoint.', 'pat obrien', 'pat obrien', 'QR-D-2', 29.9579, -90.0653, true, 'photo', 15, 'Checkpoint 2', 'Look for a tucked-away courtyard linked to a famous cocktail stop in the Quarter. Inside, one feature is memorable because fire appears above water in the same focal point. This isn’t a street-corner landmark, so you need to slip off the main path to locate it. The atmosphere is theatrical, photogenic, and often packed with visitors taking dramatic poses. If your team enters a hidden patio and immediately knows it is unique, you found the right place. Create a dramatic group pose proving you found the hidden courtyard checkpoint.', 'Create a dramatic group pose proving you found the hidden courtyard checkpoint.', 'Solved. Next clue is ready.', 'Pat O''Brien''s Flaming Fountain', 'Storm-blown team pose around the flaming fountain.', 'hard'),
  ('D', 3, 'Royal Street', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Film 5 seconds showing your team interacting with the arts or music energy of the location.', 'Film 5 seconds showing your team interacting with the arts or music energy of the location.', 'royal street', 'royal street', 'QR-D-3', 29.9589, -90.0645, true, 'video', 15, 'Checkpoint 3', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Film 5 seconds showing your team interacting with the arts or music energy of the location.', 'Film 5 seconds showing your team interacting with the arts or music energy of the location.', 'Solved. Keep pace for a strong finish.', 'Royal Street', '5-second jazz-hands video on Royal Street.', 'hard'),
  ('D', 4, 'Jackson Square', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a photo featuring the most recognizable historic or visual element in the area.', 'Take a photo featuring the most recognizable historic or visual element in the area.', 'jackson square', 'jackson square', 'QR-D-4', 29.9574, -90.0623, true, 'photo', 15, 'Checkpoint 4', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a photo featuring the most recognizable historic or visual element in the area.', 'Take a photo featuring the most recognizable historic or visual element in the area.', 'Checkpoint solved. Final checkpoint is next.', 'Jackson Square', 'Photo with cathedral or square fencing visible.', 'hard'),
  ('D', 5, 'Mulate''s', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'mulates', 'mulates', 'QR-D-5', 29.9435, -90.0703, true, 'video', 20, 'Final checkpoint', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'Route complete. Await host confirmation.', 'Mulate''s', '10-second Cajun two-step video at Mulate''s.', 'medium'),
  ('E', 1, 'Lafayette Square', 'Begin where office towers give way to a patch of green that feels older than the surrounding glass and traffic. Large oaks cast shade over lunch crowds while a raised monument anchors the center of the grounds. This stop honors a French military ally tied to early American independence. Stand where business district rush slows into a pocket of benches, iron fencing, and open lawn. If you can see a formal civic corridor nearby, you are in the right zone. Take a team photo featuring the most recognizable landmark element at this square.', 'Take a team photo featuring the most recognizable landmark element at this square.', 'lafayette square', 'lafayette square', 'QR-E-1', 29.9496, -90.0704, true, 'photo', 10, 'Checkpoint 1', 'Begin where office towers give way to a patch of green that feels older than the surrounding glass and traffic. Large oaks cast shade over lunch crowds while a raised monument anchors the center of the grounds. This stop honors a French military ally tied to early American independence. Stand where business district rush slows into a pocket of benches, iron fencing, and open lawn. If you can see a formal civic corridor nearby, you are in the right zone. Take a team photo featuring the most recognizable landmark element at this square.', 'Take a team photo featuring the most recognizable landmark element at this square.', 'Solved. Keep your team moving.', 'Lafayette Square', 'Team photo with the square and central statue area visible.', 'medium'),
  ('E', 2, 'Royal Street', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Take a photo of the most elegant or distinctive visual detail at this location.', 'Take a photo of the most elegant or distinctive visual detail at this location.', 'royal street', 'royal street', 'QR-E-2', 29.9589, -90.0645, true, 'photo', 10, 'Checkpoint 2', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Take a photo of the most elegant or distinctive visual detail at this location.', 'Take a photo of the most elegant or distinctive visual detail at this location.', 'Solved. Keep going.', 'Royal Street', 'Photo of an elegant balcony or storefront on Royal Street.', 'medium'),
  ('E', 3, 'French Market', 'Move toward the long commercial corridor where open-air stalls and vendor rows stretch block after block. This area blends shopping, snacks, souvenirs, and constant pedestrian flow. It feels historic but active, with changing displays and a market rhythm throughout the day. You should see repeated booth-style setups instead of a single storefront destination. If the scene looks like a continuous bazaar near the Quarter edge, you are in the correct zone. Take a group photo proving you found the open-air market checkpoint.', 'Take a group photo proving you found the open-air market checkpoint.', 'french market', 'french market', 'QR-E-3', 29.9615, -90.0572, true, 'photo', 15, 'Checkpoint 3', 'Move toward the long commercial corridor where open-air stalls and vendor rows stretch block after block. This area blends shopping, snacks, souvenirs, and constant pedestrian flow. It feels historic but active, with changing displays and a market rhythm throughout the day. You should see repeated booth-style setups instead of a single storefront destination. If the scene looks like a continuous bazaar near the Quarter edge, you are in the correct zone. Take a group photo proving you found the open-air market checkpoint.', 'Take a group photo proving you found the open-air market checkpoint.', 'Solved. One more clue before the finale.', 'French Market', 'Group photo by French Market sign or vendor row.', 'hard'),
  ('E', 4, 'Café du Monde', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature food challenge at this stop.', 'Take a photo proving your team completed the signature food challenge at this stop.', 'cafe du monde', 'cafe du monde', 'QR-E-4', 29.9577, -90.0621, true, 'photo', 15, 'Checkpoint 4', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature food challenge at this stop.', 'Take a photo proving your team completed the signature food challenge at this stop.', 'Solved. Final checkpoint remains.', 'Café du Monde', 'Photo showing powdered sugar mustache.', 'medium'),
  ('E', 5, 'Mulate''s', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'mulates', 'mulates', 'QR-E-5', 29.9435, -90.0703, true, 'video', 20, 'Final checkpoint', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'Route complete. Await host confirmation.', 'Mulate''s', '10-second Cajun two-step video at Mulate''s.', 'medium'),
  ('F', 1, 'Royal Street', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Take a team photo that proves you found the arts-and-music checkpoint.', 'Take a team photo that proves you found the arts-and-music checkpoint.', 'royal street', 'royal street', 'QR-F-1', 29.9589, -90.0645, true, 'photo', 10, 'Checkpoint 1', 'Find the Quarter stretch known for galleries, antiques, and buskers rather than loud nightlife crowds. Iron balconies and polished storefronts give the area a refined, curated feel. Street musicians still animate the block, but the mood is more elegant than rowdy. Window displays, art spaces, and collectors’ shops are strong visual markers here. If the surroundings feel upscale and performance-driven without neon chaos, you are in the right corridor. Take a team photo that proves you found the arts-and-music checkpoint.', 'Take a team photo that proves you found the arts-and-music checkpoint.', 'Checkpoint solved. Continue to the next clue.', 'Royal Street', 'Team photo with street musician or gallery sign on Royal Street.', 'medium'),
  ('F', 2, 'Jackson Square', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a team photo featuring the most recognizable landmark element in the area.', 'Take a team photo featuring the most recognizable landmark element in the area.', 'jackson square', 'jackson square', 'QR-F-2', 29.9574, -90.0623, true, 'photo', 15, 'Checkpoint 2', 'Find the public plaza where painters line the perimeter and portrait artists call out to passersby. Iron fencing frames open space while cathedral towers dominate the skyline behind it. A mounted historical figure stands watch over the center and appears in countless travel photos. This is one of the strongest visual crossroads of history, art, and tourism in the Quarter. If street performers, open-air artwork, and church spires all appear together, you are close. Take a team photo featuring the most recognizable landmark element in the area.', 'Take a team photo featuring the most recognizable landmark element in the area.', 'Solved. Keep moving.', 'Jackson Square', 'Team photo with St. Louis Cathedral visible.', 'hard'),
  ('F', 3, 'Café du Monde', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature treat challenge at this stop.', 'Take a photo proving your team completed the signature treat challenge at this stop.', 'cafe du monde', 'cafe du monde', 'QR-F-3', 29.9577, -90.0621, true, 'photo', 15, 'Checkpoint 3', 'Follow the aroma of chicory coffee and sweet fried dough dusted in white sugar. Tables turn quickly here as people compare powdered-sugar smiles and napkin disasters. The stop sits near major Quarter footpaths and is almost always buzzing from morning through night. You are searching for a long-running local ritual that visitors treat like a required pilgrimage. Look for lines, green-and-white visual cues, and people balancing paper bags with warm pastries. Take a photo proving your team completed the signature treat challenge at this stop.', 'Take a photo proving your team completed the signature treat challenge at this stop.', 'Checkpoint solved. Keep pace.', 'Café du Monde', 'Photo of powdered sugar mustache.', 'medium'),
  ('F', 4, 'French Market', 'Move toward the long commercial corridor where open-air stalls and vendor rows stretch block after block. This area blends shopping, snacks, souvenirs, and constant pedestrian flow. It feels historic but active, with changing displays and a market rhythm throughout the day. You should see repeated booth-style setups instead of a single storefront destination. If the scene looks like a continuous bazaar near the Quarter edge, you are in the correct zone. Take a group photo proving you found the market checkpoint.', 'Take a group photo proving you found the market checkpoint.', 'french market', 'french market', 'QR-F-4', 29.9615, -90.0572, true, 'photo', 15, 'Checkpoint 4', 'Move toward the long commercial corridor where open-air stalls and vendor rows stretch block after block. This area blends shopping, snacks, souvenirs, and constant pedestrian flow. It feels historic but active, with changing displays and a market rhythm throughout the day. You should see repeated booth-style setups instead of a single storefront destination. If the scene looks like a continuous bazaar near the Quarter edge, you are in the correct zone. Take a group photo proving you found the market checkpoint.', 'Take a group photo proving you found the market checkpoint.', 'Solved. Final checkpoint remains.', 'French Market', 'Group photo near the French Market sign.', 'hard'),
  ('F', 5, 'Mulate''s', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'mulates', 'mulates', 'QR-F-5', 29.9435, -90.0703, true, 'video', 20, 'Final checkpoint', 'Your finish is in the river-adjacent warehouse district where the vibe shifts from tourist maze to broad avenues. Music, food, and dancing combine here for a high-energy wrap-up that feels distinctly Cajun. Teams usually arrive tired and loud, then reset for one last celebratory moment. If you are still deep in tight Quarter lanes, you have not gone far enough toward the final zone. Think larger building footprints, event-night energy, and a true end-of-route atmosphere. Record a 10-second celebration video at the final destination.', 'Record a 10-second celebration video at the final destination.', 'Route complete. Await host confirmation.', 'Mulate''s', 'Cajun dance video at Mulate''s.', 'medium')
) as v(route_code, order_index, title, clue_text, task_text, unlock_answer, answer_text, unlock_qr, latitude, longitude, enable_gps, proof_type, points, public_checkpoint_label, participant_clue_text, participant_task_text_pre_solve, participant_success_text_post_solve, internal_location_name, host_verification_task_text, difficulty_level)
join routes r on r.code = v.route_code;

commit;

